openapi: 3.0.3
info:
  title: Async OCR
  description: Async REST OCR API
  version: 1.0.0
servers:
  - url: https://async-ocr.onrender.com/api
tags:
  - name: OCR Insert Request
    description: Insert text extraction request
  - name: OCR Retrieve Result
    description: Get text extraction request
paths:
  /ocr/recognition/file:
    post:
      tags:
        - OCR Insert Request
      summary: ask for text extraction
      requestBody:
        description: Enter request to extract text from the image
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                lang:
                  type: string
                  example: eng
      responses:
        '200':
          description: The request has been accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecognizeResponse'
        '400':
          description: Input not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /ocr/recognition/result:
    get:
      tags:
        - OCR Retrieve Result
      summary: retrive text extraction result (single)
      parameters:
        - name: id
          in: query
          description: Request identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Result found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OCRWorkerOutput'
              examples:
                success:
                  value:
                    confidence: 98
                    text: lorem... ipsum..
        '404':
          description: result found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OCRWorkerOutput'
              examples:
                not found error:
                  value:
                    error: NOT FOUND
  /ocr/recognition/results:
    get:
      tags:
        - OCR Retrieve Result
      summary: retrive text extraction result (list)
      parameters:
        - name: id
          in: query
          description: List of request identifier
          required: true
          schema:
            type: array
            items:
              type: string
          example: [kxSqOs359MEv0j73y42JR, gIezLJecBIMYM7nrlp03Y]
      responses:
        '200':
          description: Result found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OCRWorkerOutputExtended'
        '404':
          description: No result found for all provided ids
components:
  schemas:
    RecognizeResponse:
      type: object
      properties:
        id:
          type: string
        lang:
          type: string
          enum:
            - eng
      example:
        id: YioXNGsgXoJSCshxUo_K8
        lang: eng
    ValidationError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              value:
                type: string
              msg:
                type: string
              param:
                type: string
              location:
                type: string
      example:
        errors:
          - value: egng
            msg: Invalid Lang
            param: lang
            location: body
    OCRWorkerOutput:
      properties:
        confidence:
          type: number
        text:
          type: string
        error:
          type: string
    OCRWorkerOutputExtended:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/OCRWorkerOutput'
        - properties:
            id:
              type: string
    
